### ISSUE TITLE
Not working only got a white screen and no error message.

### ISSUE THREAD

**Issue by jmolivas** [Maslosoft/oauth2-twitter#1]
I add this library to my project using composer:

```
composer require maslosoft/oauth2-twitter:1.0.x-dev
```

Then setup my `config.yaml` file like:

```
knpu_oauth2_client:
    clients:
        twitter:
            type: generic
            provider_class: League\OAuth2\Client\Provider\Twitter

            client_id: APP_CONSUMER_KEY
            client_secret: APP_CONSUMER_SECRET

            redirect_route: connect_twitter_check
            redirect_params: {}
```

Add a TwitterController class and register two controller actions.

```
    /**
     * @Route("/connect/twitter")
     */
    public function connectAction()
    {
       ... code here ...
    }

    /**
     * @Route("/connect/twitter/check", name="connect_twitter_check")
     */
    public function connectCheckAction(Request $request)
    {
       ... code here ...
    }
```

When calling route `connect/twitter`

Got the URL redirected to `https://api.twitter.com/oauth2/token?state=` and a white screen no error message shown.
